const base = {
  topBar: {},
  mainVideoContainer: {},
  mainVideo: {},
  publisherContainer: {},
  publisher: {},
  subscriberList: {},
  subscriberContainer: {},
  subscriber: {},
  subscriberVideo: {},
  vipContainer: {},
  vipsubscriber: {},
  vipsubscriberVideo: {},
}

const styles = {
  stage: {
    ...base,
    mainVideoContainer: {
      position: 'absolute',
      width: '100vw',
      height: '100vh',
      left: 0,
      top: 0,
      zIndex: -100,
    },
    mainVideoContainerWb: {
      zIndex: -100,
      position: 'absolute',
      width: 'calc(100vw - 14rem)',
      height: 'calc(100vh - 8rem)',
      top: '4rem',
      left: '13rem',
    },
    mainVideo: {
      width: '100%',
      height: '100%',
      borderRadius: 'unset',
    },
    publisherContainer: {
      bottom: '73px',
      left: '24px',
      width: '176px',
      height: '176px',
    },
    publisher: {
      borderRadius: '20px',
      width: '100%',
      height: '100%',
    },
    subscriberList: {
      position: 'absolute',
      left: '24px',
      top: '24px',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'start',
      height: 'calc(100vh - 94px)',
      justifyContent: 'end',
      rowGap: '10px',
    },
    subscriberListWb: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'start',
      justifyContent: 'start',
      rowGap: '10px',
      width: '15%',
      minWidth: '10rem',
    },
    subscriberListAnon: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'start',
      height: 'calc(100vh - 24px)',
      justifyContent: 'start',
      rowGap: '10px',
      width: 'fit-content',
    },
    subscriberListWbAnon: {
      // position: 'absolute',
      // left: '24px',
      // top: '24px',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'start',
      height: 'calc(100vh - 24px)',
      justifyContent: 'start',
      rowGap: '10px',
      width: 'fit-content',
    },
    subscriberContainer: {
      display: 'flex',
      // overflowY: 'auto',
      // flexGrow: 9,
      flexDirection: 'column',
      aspectRatio: '0.25',
      paddingRight: '20px',
      alignItems: 'center',
      height: '100%',
      rowGap: '10px',
      minWidth: '100% !important',
    },
    subscriber: {
      maxHeight: '124px',
      flexGrow: 1,
      height: '100%',
      borderRadius: '20px',
      backgroundColor: 'black',
      width: '100%',
    },
    subscriberVideo: {
      borderRadius: '20px',
      backgroundColor: 'black',
      width: '100%',
    },
    vipContainer: {
      position: 'absolute',
      right: '24px',
      top: '80px',
    },
    vipsubscriber: {
      height: 'calc(100vh / 3)',
      aspectRatio: '1 / 1',
    },
    vipsubscriberVideo: {
      width: '100%',
      height: '100%',
      backgroundColor: 'black',
      borderRadius: '20px',
    },
  },
  fullscreen: {
    ...base,
    mainVideoContainer: {
      position: 'absolute',
      right: 24,
      bottom: 86,
      height: '250px',
      maxWidth: '390px',
      zIndex: -100,
    },
    mainVideoContainerWb: {
      zIndex: -100,
      position: 'relative',
      height: '1px',
      maxWidth: '1px',
      top: '4rem',
      left: '50%',
    },
    mainVideo: {
      width: '100%',
      height: '100%',
      borderRadius: '20px',
    },
    publisherContainer: {
      position: 'absolute',
      bottom: '73px',
      left: '24px',
      width: '176px',
      height: '176px',
    },
    publisher: {
      borderRadius: '20px',
      width: '100%',
      height: '100%',
    },
    subscriberList: {
      position: 'absolute',
      width: '100%',
      height: 'calc(100vh - 480px)',
      display: 'flex',
      flexDirection: 'column',
      alignContent: 'center',
      justifyContent: 'center',
    },
    subscriberListWb: {
      position: 'absolute',
      width: '100%',
      height: '100%',
      maxHeight: 'calc(100vh - 9rem)',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      top: '4rem',
      maxWidth: '90%',
      padding: '15px',
    },
    subscriberListAnon: {
      position: 'absolute',
      width: '100%',
      height: 'calc(100vh - 480px)',
      display: 'flex',
      flexDirection: 'column',
      alignContent: 'center',
      justifyContent: 'center',
      top: '5rem',
    },
    subscriberListWbAnon: {
      position: 'absolute',
      width: '100%',
      height: 'calc(100vh - 10rem)',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      top: '5rem',
    },
    subscriberContainer: {
      padding: '0 48px',
      display: 'grid',
      gridGap: '20px',
      gridTemplateRows: 'calc((100% / 2)) calc((100% / 2))',
      gridTemplateColumns:
        'calc((100% / 4) - 12px) calc((100% / 4) - 12px) calc((100% / 4) - 12px) calc((100% / 4) - 12px)',
      height: '100%',
      marginTop: '0!important',
      justifyContent: 'center',
    },
    subscriberContainerFull: {
      gap: '10px',
      justifyContent: 'center',
      overflow: 'hidden',
    },
    subscriber: {
      height: '100%',
      borderRadius: '20px',
      // backgroundColor: 'black',
      aspectRatio: '1 / 1',
      padding: '0 !important',
    },
    subscriberVideo: {
      borderRadius: '20px',
      backgroundColor: 'black',
      aspectRatio: '1 / 1',
    },
    publisherVideo: {
      height: '100%',
      borderRadius: '20px',
      backgroundColor: 'black',
      aspectRatio: '1 / 1',
    },
    vipContainer: {
      position: 'absolute',
      bottom: '80px',
      left: '24px',
    },
    vipsubscriber: {
      height: '250px',
      aspectRatio: '1 / 1',
    },
    vipsubscriberVideo: {
      width: '100%',
      height: '100%',
      backgroundColor: 'black',
      borderRadius: '20px',
    },
  },
  empty: {
    ...base,
    topBar: {
      display: 'none!important',
    },
    mainVideoContainerWb: {
      position: 'absolute',
      width: '100vw',
      height: '100vh',
      left: 0,
      top: 0,
      zIndex: -100,
      backgroundColor: 'black',
    },
    mainVideoContainer: {
      position: 'absolute',
      width: '100vw',
      height: '100vh',
      left: 0,
      top: 0,
      zIndex: -100,
    },
    mainVideo: {
      width: '100%',
      height: '100%',
      borderRadius: 'unset',
    },
    publisherContainer: {
      bottom: '73px',
      left: '24px',
      width: '176px',
      height: '176px',
    },
    publisher: {
      borderRadius: '20px',
      width: '100%',
      height: '100%',
    },
    subscriberList: {
      opacity: 0.3,
      position: 'absolute',
      left: '24px',
      top: '24px',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'start',
      height: 'calc(100vh - 94px)',
      justifyContent: 'end',
      rowGap: '10px',
    },
    subscriberListWb: {
      opacity: 0.3,
      position: 'absolute',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'start',
      // height: 'calc(100vh - 94px)',
      justifyContent: 'end',
      rowGap: '10px',
      zIndex: '-200',
    },
    subscriberContainer: {
      display: 'flex',
      overflowY: 'auto',
      // flexGrow: 9,
      flexDirection: 'column',
      width: '144px',
      aspectRatio: '0.25',
      paddingRight: '20px',
      alignItems: 'center',
      height: '100%',
      rowGap: '10px',
    },
    subscriber: {
      maxHeight: '124px',
      flexGrow: 1,
      height: '100%',
      borderRadius: '20px',
      // backgroundColor: 'black',
      width: '100%',
    },
    subscriberVideo: {
      borderRadius: '20px',
      backgroundColor: 'black',
      width: '100%',
    },
    vipContainer: {
      position: 'absolute',
      right: '24px',
      top: '80px',
    },
    vipsubscriber: {
      height: 'calc(100vh / 3)',
      aspectRatio: '1 / 1',
    },
    vipsubscriberVideo: {
      width: '100%',
      height: '100%',
      backgroundColor: 'black',
      borderRadius: '20px',
    },
  },
}

export default styles
