import { ICountry } from '../models/Country'

export const COUNTRIES: ICountry[] = [
  { label: 'Afghanistan', code: 'AFG' },
  { label: 'Albania', code: 'ALB' },
  { label: 'Algeria', code: 'DZA' },
  { label: 'American Samoa', code: 'ASM' },
  { label: 'Andorra', code: 'AND' },
  { label: 'Angola', code: 'AGO' },
  { label: 'Anguilla', code: 'AIA' },
  { label: 'Antarctica', code: 'ATA' },
  { label: 'Antigua and Barbuda', code: 'ATG' },
  { label: 'Argentina', code: 'ARG' },
  { label: 'Armenia', code: 'ARM' },
  { label: 'Aruba', code: 'ABW' },
  { label: 'Australia', code: 'AUS' },
  { label: 'Austria', code: 'AUT' },
  { label: 'Azerbaijan', code: 'AZE' },
  { label: 'Bahamas', code: 'BHS' },
  { label: 'Bahrain', code: 'BHR' },
  { label: 'Bangladesh', code: 'BGD' },
  { label: 'Barbados', code: 'BRB' },
  { label: 'Belarus', code: 'BLR' },
  { label: 'Belgium', code: 'BEL' },
  { label: 'Belize', code: 'BLZ' },
  { label: 'Benin', code: 'BEN' },
  { label: 'Bermuda', code: 'BMU' },
  { label: 'Bhutan', code: 'BTN' },
  { label: 'Bolivia', code: 'BOL' },
  { label: 'Bosnia and Herzegovina', code: 'BIH' },
  { label: 'Botswana', code: 'BWA' },
  { label: 'Bouvet Island', code: 'BVT' },
  { label: 'Brazil', code: 'BRA' },
  { label: 'British Virgin Islands', code: 'VGB' },
  { label: 'Brunei Darussalam', code: 'BRN' },
  { label: 'Bulgaria', code: 'BGR' },
  { label: 'Burkina Faso', code: 'BFA' },
  { label: 'Burundi', code: 'BDI' },
  { label: 'Cabo Verde', code: 'CPV' },
  { label: 'Cambodia', code: 'KHM' },
  { label: 'Cameroon', code: 'CMR' },
  { label: 'Canada', code: 'CAN' },
  { label: 'Cayman Islands', code: 'CYM' },
  { label: 'Central African Republic', code: 'CAF' },
  { label: 'Chad', code: 'TCD' },
  { label: 'Chile', code: 'CHL' },
  { label: 'China', code: 'CHN' },
  { label: 'Christmas Island', code: 'CXR' },
  { label: 'Cocos (Keeling) Islands', code: 'CCK' },
  { label: 'Colombia', code: 'COL' },
  { label: 'Comoros', code: 'COM' },
  { label: 'DR Congo', code: 'COD' },
  { label: 'Congo', code: 'COG' },
  { label: 'Cook Islands', code: 'COK' },
  { label: 'Costa Rica', code: 'CRI' },
  { label: 'Croatia', code: 'HRV' },
  { label: 'Cuba', code: 'CUB' },
  { label: 'Curaçao', code: 'CUW' },
  { label: 'Cyprus', code: 'CYP' },
  { label: 'Czechia', code: 'CZE' },
  { label: "Côte d'Ivoire", code: 'CIV' },
  { label: 'Denmark', code: 'DNK' },
  { label: 'Djibouti', code: 'DJI' },
  { label: 'Dominica', code: 'DMA' },
  { label: 'Dominican Republic', code: 'DOM' },
  { label: 'Ecuador', code: 'ECU' },
  { label: 'Egypt', code: 'EGY' },
  { label: 'El Salvador', code: 'SLV' },
  { label: 'Equatorial Guinea', code: 'GNQ' },
  { label: 'Eritrea', code: 'ERI' },
  { label: 'Estonia', code: 'EST' },
  { label: 'Eswatini', code: 'SWZ' },
  { label: 'Ethiopia', code: 'ETH' },
  { label: 'Faroe Islands', code: 'FRO' },
  { label: 'Fiji', code: 'FJI' },
  { label: 'Finland', code: 'FIN' },
  { label: 'France', code: 'FRA' },
  { label: 'French Guiana', code: 'GUF' },
  { label: 'French Polynesia', code: 'PYF' },
  { label: 'Gabon', code: 'GAB' },
  { label: 'Gambia', code: 'GMB' },
  { label: 'Georgia', code: 'GEO' },
  { label: 'Germany', code: 'DEU' },
  { label: 'Ghana', code: 'GHA' },
  { label: 'Gibraltar', code: 'GIB' },
  { label: 'Greece', code: 'GRC' },
  { label: 'Greenland', code: 'GRL' },
  { label: 'Grenada', code: 'GRD' },
  { label: 'Guadeloupe', code: 'GLP' },
  { label: 'Guam', code: 'GUM' },
  { label: 'Guatemala', code: 'GTM' },
  { label: 'Guernsey', code: 'GGY' },
  { label: 'Guinea', code: 'GIN' },
  { label: 'Guinea-Bissau', code: 'GNB' },
  { label: 'Guyana', code: 'GUY' },
  { label: 'Haiti', code: 'HTI' },
  { label: 'Holy See', code: 'VAT' },
  { label: 'Honduras', code: 'HND' },
  { label: 'Hong Kong', code: 'HKG' },
  { label: 'Hungary', code: 'HUN' },
  { label: 'Iceland', code: 'ISL' },
  { label: 'India', code: 'IND' },
  { label: 'Indonesia', code: 'IDN' },
  { label: 'Iran', code: 'IRN' },
  { label: 'Iraq', code: 'IRQ' },
  { label: 'Ireland', code: 'IRL' },
  { label: 'Isle of Man', code: 'IMN' },
  { label: 'Israel', code: 'ISR' },
  { label: 'Italy', code: 'ITA' },
  { label: 'Jamaica', code: 'JAM' },
  { label: 'Japan', code: 'JPN' },
  { label: 'Jersey', code: 'JEY' },
  { label: 'Jordan', code: 'JOR' },
  { label: 'Kazakhstan', code: 'KAZ' },
  { label: 'Kenya', code: 'KEN' },
  { label: 'Kiribati', code: 'KIR' },
  { label: 'North Korea', code: 'PRK' },
  { label: 'South Korea', code: 'KOR' },
  { label: 'Kuwait', code: 'KWT' },
  { label: 'Kyrgyzstan', code: 'KGZ' },
  { label: 'Laos', code: 'LAO' },
  { label: 'Latvia', code: 'LVA' },
  { label: 'Lebanon', code: 'LBN' },
  { label: 'Lesotho', code: 'LSO' },
  { label: 'Liberia', code: 'LBR' },
  { label: 'Libya', code: 'LBY' },
  { label: 'Liechtenstein', code: 'LIE' },
  { label: 'Lithuania', code: 'LTU' },
  { label: 'Luxembourg', code: 'LUX' },
  { label: 'Macao', code: 'MAC' },
  { label: 'Madagascar', code: 'MDG' },
  { label: 'Malawi', code: 'MWI' },
  { label: 'Malaysia', code: 'MYS' },
  { label: 'Maldives', code: 'MDV' },
  { label: 'Mali', code: 'MLI' },
  { label: 'Malta', code: 'MLT' },
  { label: 'Marshall Islands', code: 'MHL' },
  { label: 'Martinique', code: 'MTQ' },
  { label: 'Mauritania', code: 'MRT' },
  { label: 'Mauritius', code: 'MUS' },
  { label: 'Mayotte', code: 'MYT' },
  { label: 'Mexico', code: 'MEX' },
  { label: 'Micronesia', code: 'FSM' },
  { label: 'Moldova', code: 'MDA' },
  { label: 'Monaco', code: 'MCO' },
  { label: 'Mongolia', code: 'MNG' },
  { label: 'Montenegro', code: 'MNE' },
  { label: 'Montserrat', code: 'MSR' },
  { label: 'Morocco', code: 'MAR' },
  { label: 'Mozambique', code: 'MOZ' },
  { label: 'Myanmar', code: 'MMR' },
  { label: 'Namibia', code: 'NAM' },
  { label: 'Nauru', code: 'NRU' },
  { label: 'Nepal', code: 'NPL' },
  { label: 'Netherlands', code: 'NLD' },
  { label: 'New Caledonia', code: 'NCL' },
  { label: 'New Zealand', code: 'NZL' },
  { label: 'Nicaragua', code: 'NIC' },
  { label: 'Niger', code: 'NER' },
  { label: 'Nigeria', code: 'NGA' },
  { label: 'Niue', code: 'NIU' },
  { label: 'Norfolk Island', code: 'NFK' },
  { label: 'Northern Mariana Islands', code: 'MNP' },
  { label: 'Norway', code: 'NOR' },
  { label: 'Oman', code: 'OMN' },
  { label: 'Pakistan', code: 'PAK' },
  { label: 'Palau', code: 'PLW' },
  { label: 'State of Palestine', code: 'PSE' },
  { label: 'Panama', code: 'PAN' },
  { label: 'Papua New Guinea', code: 'PNG' },
  { label: 'Paraguay', code: 'PRY' },
  { label: 'Peru', code: 'PER' },
  { label: 'Philippines', code: 'PHL' },
  { label: 'Pitcairn', code: 'PCN' },
  { label: 'Poland', code: 'POL' },
  { label: 'Portugal', code: 'PRT' },
  { label: 'Puerto Rico', code: 'PRI' },
  { label: 'Qatar', code: 'QAT' },
  { label: 'Macedonia', code: 'MKD' },
  { label: 'Romania', code: 'ROU' },
  { label: 'Russia', code: 'RUS' },
  { label: 'Rwanda', code: 'RWA' },
  { label: 'Réunion', code: 'REU' },
  { label: 'Saint Barthélemy', code: 'BLM' },
  { label: 'Saint Helena', code: 'SHN' },
  { label: 'Saint Kitts and Nevis', code: 'KNA' },
  { label: 'Saint Lucia', code: 'LCA' },
  { label: 'Saint Martin', code: 'MAF' },
  { label: 'Saint Pierre and Miquelon', code: 'SPM' },
  { label: 'Saint Vincent and the Grenadines', code: 'VCT' },
  { label: 'Samoa', code: 'WSM' },
  { label: 'San Marino', code: 'SMR' },
  { label: 'Sao Tome and Principe', code: 'STP' },
  { label: 'Saudi Arabia', code: 'SAU' },
  { label: 'Senegal', code: 'SEN' },
  { label: 'Serbia', code: 'SRB' },
  { label: 'Seychelles', code: 'SYC' },
  { label: 'Sierra Leone', code: 'SLE' },
  { label: 'Singapore', code: 'SGP' },
  { label: 'Sint Maarten (Dutch part)', code: 'SXM' },
  { label: 'Slovakia', code: 'SVK' },
  { label: 'Slovenia', code: 'SVN' },
  { label: 'Solomon Islands', code: 'SLB' },
  { label: 'Somalia', code: 'SOM' },
  { label: 'South Africa', code: 'ZAF' },
  { label: 'South Sudan', code: 'SSD' },
  { label: 'Spain', code: 'ESP' },
  { label: 'Sri Lanka', code: 'LKA' },
  { label: 'Sudan', code: 'SDN' },
  { label: 'Suriname', code: 'SUR' },
  { label: 'Svalbard and Jan Mayen', code: 'SJM' },
  { label: 'Sweden', code: 'SWE' },
  { label: 'Switzerland', code: 'CHE' },
  { label: 'Syrian Arab Republic', code: 'SYR' },
  { label: 'Taiwan (Province of China)', code: 'TWN' },
  { label: 'Tajikistan', code: 'TJK' },
  { label: 'Tanzania', code: 'TZA' },
  { label: 'Thailand', code: 'THA' },
  { label: 'Timor-Leste', code: 'TLS' },
  { label: 'Togo', code: 'TGO' },
  { label: 'Tokelau', code: 'TKL' },
  { label: 'Tonga', code: 'TON' },
  { label: 'Trinidad and Tobago', code: 'TTO' },
  { label: 'Tunisia', code: 'TUN' },
  { label: 'Turkey', code: 'TUR' },
  { label: 'Turkmenistan', code: 'TKM' },
  { label: 'Turks and Caicos Islands', code: 'TCA' },
  { label: 'Tuvalu', code: 'TUV' },
  { label: 'Uganda', code: 'UGA' },
  { label: 'Ukraine', code: 'UKR' },
  { label: 'United Arab Emirates', code: 'ARE' },
  { label: 'United Kingdom', code: 'GBR' },
  { label: 'United States', code: 'USA' },
  { label: 'Uruguay', code: 'URY' },
  { label: 'U.S. Virgin Islands', code: 'VIR' },
  { label: 'Uzbekistan', code: 'UZB' },
  { label: 'Vanuatu', code: 'VUT' },
  { label: 'Venezuela', code: 'VEN' },
  { label: 'Vietnam', code: 'VNM' },
  { label: 'Wallis and Futuna', code: 'WLF' },
  { label: 'Western Sahara', code: 'ESH' },
  { label: 'Yemen', code: 'YEM' },
  { label: 'Zambia', code: 'ZMB' },
  { label: 'Zimbabwe', code: 'ZWE' },
]
