name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build_release:
      name: build_release
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [18.x]
      steps:
      - uses: actions/checkout@v3
      - name: build_watchparty
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install && npm run build:webapp:watchparty
      - name: build_webinar
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install && npm run build:webapp:webinar
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload watchparty
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/truetime-watchparty.zip
          asset_name: truetime-watchparty.zip
          asset_content_type: application/zip
      - name: upload webinar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/truetime-webinar.zip
          asset_name: truetime-webinar.zip
          asset_content_type: application/zip
